### ISSUE TITLE
Link telegram "HR feat. ICT (by Lavoro Digitale italia" - Non funzionante

### ISSUE THREAD

**Issue by Wisheechia** [GuidoPenta/awesome-italian-tech-communities#23]
Il link telegram a `[HR feat. ICT (by Lavoro Digitale italia)](https://t.me/c/1358339086)` non funziona correttamente, mi riporta alla homepage di telegram, non al gruppo. 
Non sono iscritto al gruppo, quindi non so se questo tipo di link è inutilizzabile dall'esterno (non è il classico t.me/nome_del_gruppo)

**Comment by GuidoPenta** [comment]
Grazie mille, l'ho aggiornato!
